Repository grafana/grafana-plugin-examples, pull requests merged in 2023-01, with the labels that each got.

#119 Datasource-http: Improve error handling and error messages
  examples/datasource-http/src/DataSource.ts
Labels: enhancement

#123 Adding dependabot config
  .github/dependabot.yml
Labels: dependencies

#124 Adding link in main readme to "app with dashboards" example
  README.md
Labels: documentation
