Repository grafana/grafana-plugin-examples, pull requests merged in 2023-10, with the labels that each got.

#204 OnBehalfOf: Add Grafana configuration to the README
  examples/app-with-on-behalf-of-auth/README.md
Labels: documentation

#206 Docs: Update links to dev portal
  examples/app-basic/README.md
  examples/app-with-backend/README.md
  examples/app-with-dashboards/README.md
  examples/app-with-on-behalf-of-auth/README.md
  examples/datasource-basic/README.md
  examples/panel-datalinks/README.md
Labels: documentation

#205 Chore: Bump grafana-plugin-sdk-go to v0.179.0
  examples/app-with-backend/go.mod
  examples/app-with-backend/go.sum
  examples/app-with-backend/pkg/plugin/app.go
  examples/app-with-backend/pkg/plugin/resources.go
  examples/app-with-backend/pkg/plugin/resources_test.go
  examples/app-with-on-behalf-of-auth/go.mod
  examples/app-with-on-behalf-of-auth/go.sum
  examples/app-with-on-behalf-of-auth/pkg/plugin/app.go
  examples/datasource-basic/go.mod
  examples/datasource-basic/go.sum
  examples/datasource-basic/pkg/plugin/datasource.go
  examples/datasource-http-backend/cmd/server/main.go
  examples/datasource-http-backend/go.mod
  examples/datasource-http-backend/go.sum
  examples/datasource-http-backend/pkg/plugin/datasource.go
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.mod
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.sum
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/pkg/plugin/datasource.go
Labels: dependencies

#208 Bump go plugin SDK version to 0.184.0
  examples/app-with-backend/go.mod
  examples/app-with-backend/go.sum
  examples/app-with-on-behalf-of-auth/go.mod
  examples/app-with-on-behalf-of-auth/go.sum
  examples/app-with-on-behalf-of-auth/pkg/plugin/app.go
  examples/datasource-basic/go.mod
  examples/datasource-basic/go.sum
  examples/datasource-http-backend/go.mod
  examples/datasource-http-backend/go.sum
  examples/datasource-http-backend/pkg/plugin/datasource.go
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.mod
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.sum
Labels: dependencies

#210 Chore: Bump grafana-plugin-sdk-go to v0.187.0
  examples/app-with-backend/go.mod
  examples/app-with-backend/go.sum
  examples/app-with-on-behalf-of-auth/go.mod
  examples/app-with-on-behalf-of-auth/go.sum
  examples/datasource-basic/go.mod
  examples/datasource-basic/go.sum
  examples/datasource-http-backend/go.mod
  examples/datasource-http-backend/go.sum
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.mod
  examples/datasource-streaming-backend-websocket/streaming-backend-websocket-plugin/go.sum
Labels: chore

#211 Add contextual logger to backend plugin examples
  examples/app-with-backend/pkg/plugin/resources.go
  examples/datasource-http-backend/pkg/plugin/datasource.go
Labels: enhancement
